"""empty message

Revision ID: 1c9071d55493
Revises: d15ee6686cb1
Create Date: 2023-04-14 02:16:46.353453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9071d55493'
down_revision = 'd15ee6686cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bite_exer_order_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('bitex_vendor_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('offer', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('liked_by', sa.PickleType(), nullable=False))
        batch_op.add_column(sa.Column('viewed_by', sa.PickleType(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_bitex_vendor_menu_kitchen_name', 'bitex_vendor', ['kitchen_name'], ['kitchen_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitex_vendor_menu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'bitex_vendor', ['kitchen_name'], ['bite_id'])
        batch_op.drop_column('viewed_by')
        batch_op.drop_column('liked_by')
        batch_op.drop_column('offer')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('bite_exer_order_history', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
