"""empty message

Revision ID: d15ee6686cb1
Revises: 
Create Date: 2023-04-01 17:35:32.538719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15ee6686cb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitex_driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_status', sa.String(length=7), nullable=False),
    sa.Column('account_status', sa.String(length=12), nullable=False),
    sa.Column('bite_id', sa.String(length=15), nullable=False),
    sa.Column('photo', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Numeric(precision=65, scale=1, decimal_return_scale=1), nullable=False),
    sa.Column('national_identification_number', sa.Integer(), nullable=True),
    sa.Column('driver_license', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bite_id'], ['bite_exer.bite_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bite_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('bitex_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_status', sa.String(length=12), nullable=False),
    sa.Column('bite_id', sa.String(length=15), nullable=False),
    sa.Column('kitchen_name', sa.String(length=200), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=23), nullable=False),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('opening_hour', sa.Time(), nullable=True),
    sa.Column('closing_hour', sa.Time(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=65, scale=1, decimal_return_scale=1), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bite_id'], ['bite_exer.bite_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bite_id'),
    sa.UniqueConstraint('kitchen_name'),
    mysql_engine='InnoDB'
    )
    op.create_table('bitex_driver_vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('bite_id', sa.String(length=15), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('license_number_plate', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('photo', sa.PickleType(), nullable=False),
    sa.Column('license_certificate', sa.PickleType(), nullable=False),
    sa.Column('verification_status', sa.String(length=12), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bite_id'], ['bitex_driver.bite_id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('bitex_vendor_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=13), nullable=False),
    sa.Column('kitchen_name', sa.String(length=200), nullable=False),
    sa.Column('bitem_id', sa.String(length=14), nullable=False),
    sa.Column('bitem', sa.String(length=20), nullable=False),
    sa.Column('image', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=65, scale=2, decimal_return_scale=2), nullable=False),
    sa.Column('average_prep_time', sa.Time(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kitchen_name'], ['bitex_vendor.bite_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bitem_id'),
    mysql_engine='InnoDB'
    )
    op.drop_table('bite_driver_vehicle')
    op.drop_table('bite_driver')
    op.drop_table('bite_vendor_menu')
    op.drop_table('bite_vendor')
    with op.batch_alter_table('bite_exer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer_id', sa.String(length=15), nullable=True))
        batch_op.drop_column('referral_id')

    with op.batch_alter_table('bite_exer_order_history', schema=None) as batch_op:
        batch_op.alter_column('prep_time',
               existing_type=sa.INTEGER(),
               type_=sa.Time(),
               nullable=True)
        batch_op.alter_column('delivery_time',
               existing_type=sa.INTEGER(),
               type_=sa.Time(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bite_exer_order_history', schema=None) as batch_op:
        batch_op.alter_column('delivery_time',
               existing_type=sa.Time(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('prep_time',
               existing_type=sa.Time(),
               type_=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('bite_exer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_id', sa.VARCHAR(length=15), nullable=True))
        batch_op.drop_column('referrer_id')

    op.create_table('bite_vendor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_status', sa.VARCHAR(length=12), nullable=False),
    sa.Column('bite_id', sa.VARCHAR(length=15), nullable=False),
    sa.Column('kitchen_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('website_url', sa.TEXT(), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=23), nullable=False),
    sa.Column('bio', sa.VARCHAR(length=200), nullable=True),
    sa.Column('opening_hour', sa.VARCHAR(length=5), nullable=True),
    sa.Column('closing_hour', sa.VARCHAR(length=5), nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=65, scale=1), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('date_updated', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['bite_id'], ['bite_exer.bite_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bite_id'),
    sa.UniqueConstraint('kitchen_name')
    )
    op.create_table('bite_vendor_menu',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=13), nullable=False),
    sa.Column('kitchen_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('bitem_id', sa.VARCHAR(length=14), nullable=False),
    sa.Column('bitem', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image', sa.VARCHAR(length=24), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=65, scale=2), nullable=False),
    sa.Column('average_prep_time', sa.INTEGER(), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=False),
    sa.Column('date_updated', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['kitchen_name'], ['bite_vendor.bite_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bitem_id')
    )
    op.create_table('bite_driver',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('active_status', sa.VARCHAR(length=7), nullable=False),
    sa.Column('account_status', sa.VARCHAR(length=12), nullable=False),
    sa.Column('bite_id', sa.VARCHAR(length=15), nullable=False),
    sa.Column('photo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=65, scale=1), nullable=False),
    sa.Column('national_identification_number', sa.INTEGER(), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('date_updated', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['bite_id'], ['bite_exer.bite_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bite_id')
    )
    op.create_table('bite_driver_vehicle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('bite_id', sa.VARCHAR(length=15), nullable=False),
    sa.Column('driver_license', sa.VARCHAR(length=100), nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=20), nullable=False),
    sa.Column('model', sa.VARCHAR(length=20), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('license_number_plate', sa.VARCHAR(length=20), nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), nullable=False),
    sa.Column('photo', sa.BLOB(), nullable=False),
    sa.Column('license_certificate', sa.BLOB(), nullable=False),
    sa.Column('verification_status', sa.VARCHAR(length=12), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=False),
    sa.Column('date_updated', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['bite_id'], ['bite_driver.bite_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bitex_vendor_menu')
    op.drop_table('bitex_driver_vehicle')
    op.drop_table('bitex_vendor')
    op.drop_table('bitex_driver')
    # ### end Alembic commands ###
